// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCLX5OwQ8kWtWoLC-c2FnHVCZOJOf3elQ',
    appId: '1:660120873813:web:40d4ee3363b9bf64bf5ddc',
    messagingSenderId: '660120873813',
    projectId: 'fir-10a8b',
    authDomain: 'fir-10a8b.firebaseapp.com',
    storageBucket: 'fir-10a8b.appspot.com',
    measurementId: 'G-05577W3J2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ59CeJoIrfxiPctpeQ7pTrCShEmHNNr0',
    appId: '1:660120873813:android:4f2da3cac0ce97dcbf5ddc',
    messagingSenderId: '660120873813',
    projectId: 'fir-10a8b',
    storageBucket: 'fir-10a8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuKVu4mAzhdTa6TV5Ugujh0V90kOvZAE8',
    appId: '1:660120873813:ios:c2af64b5d1fc4df0bf5ddc',
    messagingSenderId: '660120873813',
    projectId: 'fir-10a8b',
    storageBucket: 'fir-10a8b.appspot.com',
    iosBundleId: 'com.example.assigment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuKVu4mAzhdTa6TV5Ugujh0V90kOvZAE8',
    appId: '1:660120873813:ios:c2af64b5d1fc4df0bf5ddc',
    messagingSenderId: '660120873813',
    projectId: 'fir-10a8b',
    storageBucket: 'fir-10a8b.appspot.com',
    iosBundleId: 'com.example.assigment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCLX5OwQ8kWtWoLC-c2FnHVCZOJOf3elQ',
    appId: '1:660120873813:web:20cac71be7cde242bf5ddc',
    messagingSenderId: '660120873813',
    projectId: 'fir-10a8b',
    authDomain: 'fir-10a8b.firebaseapp.com',
    storageBucket: 'fir-10a8b.appspot.com',
    measurementId: 'G-XY98D5W5FC',
  );
}
